[[main]]
  name = "about"
  pageRef = "/"
  weight = 10

[[main]]
  name = "news"
  pageRef = "/news"
  weight = 15

[[main]]
  name = "publications"
  pageRef = "/publications"
  weight = 20

[[main]]
  name = "codes"
  pageRef = "/codes"
  weight = 30

[[main]]
  name = "cv"
  pageRef = "/cv"
  weight = 40
